import { RawSheetRow } from "@/features/executive-report/types/report.types";

export const reportDemoData: RawSheetRow[] = [
  {
    "Tipo de item": "Historia",
    Chave: "EST-101",
    Resumo: "Melhorar conciliacao de eventos do eSocial",
    Responsavel: "Marina",
    Status: "Em andamento",
    Criado: "2026-03-01",
    "Atualizado(a)": "2026-03-16",
    Categorias: "eSocial",
  },
  {
    "Tipo de item": "Bug",
    Chave: "EST-097",
    Resumo: "Corrigir bloqueio na admissao com documento estrangeiro",
    Responsavel: "Joao",
    Status: "AGUARDANDO REVISAO",
    Criado: "2026-02-25",
    "Atualizado(a)": "2026-03-15",
    Categorias: "Admissao",
  },
  {
    "Tipo de item": "Tarefa",
    Chave: "EST-083",
    Resumo: "Preparar pacote de subida para rotinas de ferias",
    Responsavel: "Ana",
    Status: "SUBIR PARA PRODUCAO",
    Criado: "2026-02-20",
    "Atualizado(a)": "2026-03-14",
    Categorias: "Ferias",
  },
  {
    "Tipo de item": "Historia",
    Chave: "EST-052",
    Resumo: "Publicar ajuste de eventos complementares",
    Responsavel: "Carlos",
    Status: "PRODUCTION",
    Criado: "2026-01-16",
    "Atualizado(a)": "2026-03-13",
    Categorias: "eSocial, Folha",
  },
  {
    "Tipo de item": "Tarefa",
    Chave: "EST-115",
    Resumo: "Refinar regras de validacao da planilha de admissao",
    Responsavel: "Marina",
    Status: "Tarefas pendentes",
    Criado: "2026-03-10",
    "Atualizado(a)": "2026-03-10",
    Categorias: "Admissao",
  },
];
